### ISSUE TITLE
Hashicorp Config Language (HCL) support

### ISSUE THREAD

**Issue by mike-sol** [afnanenayet/diffsitter#153]
This project is super useful and I am trying to work it into my workflow. 

I live in HCL, the language of Terraform, a lot of the time, and it would be awesome to be able to compare HCL changes with this AST-aware method.

I'm aware the tree-sitter project does not presently support HCL. Should I push an issue up there, and link it here, or something like that?

**Comment by afnanenayet** [comment]
Yeah I think that's the move - diffsitter fully relies on tree-sitter to generate ASTs

**Comment by mike-sol** [comment]
In that issue @maxbrunsfeld pointed out the existence of https://github.com/mitchellh/tree-sitter-hcl
Is that something that could be rolled in here?

**Comment by afnanenayet** [comment]
Yep! Seems like a standard tree-sitter grammar
