### ISSUE TITLE
Handle unknown files gracefully

### ISSUE THREAD

**Issue by j-martin** [afnanenayet/diffsitter#160]
**Is your feature request related to a problem? Please describe.**

In this [discussion](https://github.com/afnanenayet/diffsitter/pull/157) which spanned from https://github.com/afnanenayet/diffsitter/issues/155 it was noted that diffsitter cannot handle files it does not have the grammar for. This is an issue when trying to show diff in a git repository with a mix of supported and unsupported files.

**Describe the solution you'd like**
It would be nice if diffsitter was able to show diffs the same way that `diff` shows diff when the files are not supported. I'd be happy even if it only invoked `diff` in the background

**Describe alternatives you've considered**
With an intermediary script I guess it could achieve naively this way: `diffsitter "$@" || diff "$@"`. It has been suggested to use `.gitattribute` for [the git case](https://github.com/afnanenayet/diffsitter/pull/157#issuecomment-883302611), but this won't scale beyond the `git` usecase.

**Comment by afnanenayet** [comment]
Yeah I suppose we could do that. I think I'd prefer having this be a configurable option with an error being the default behavior, maybe have a "passthrough" option that invokes another executable if diffsitter doesn't support the file type?

**Comment by afnanenayet** [comment]
Hey, sorry about this, missed your comment, but I pushed [`0.6.7`](https://github.com/afnanenayet/diffsitter/releases/tag/v0.6.7) recently, and also set up [nightly builds](https://github.com/afnanenayet/diffsitter/releases/tag/nightly).

**Comment by j-martin** [comment]
No worries!

Just confirming the change works well. I just had to figure out where exactly to put the config.  https://github.com/afnanenayet/diffsitter/issues/249
