### ISSUE TITLE
Latest stable version is missing Windows release

### ISSUE THREAD

**Issue by tech189** [afnanenayet/diffsitter#509]
The latest stable version, 0.7.2 is missing a `diffsitter-x86_64-pc-windows-msvc.zip` release. As such, the Scoop package is out of date. Could you check this out please? Thanks in advance.

**Comment by afnanenayet** [comment]
I actually disabled the Windows releases at some point because the CI was failing and I couldn't figure out the issue (and back then I didn't have a Windows machine). I made a PR to add the Windows target back into the CI. Hoping that works, if not, I'll investigate what the issue is.

**Comment by afnanenayet** [comment]
The windows release is back with [v0.7.3](https://github.com/afnanenayet/diffsitter/releases/tag/v0.7.3)
